# jekyll-paginate configuration
# paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none

sass:
  sass_dir: assets/css
  style: :compressed

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Jekyll Starter Kit"
description:	       "A simple framework for starting your own Jekyll project"
author:              "Paul Le"
